# Generated by Django 5.2 on 2025-04-24 03:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_saude", "0002_alter_provider_user_alter_person_user_delete_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="concept",
            name="domain_id",
        ),
        migrations.RemoveField(
            model_name="person",
            name="person_id",
        ),
        migrations.AddField(
            model_name="concept",
            name="domain",
            field=models.ForeignKey(
                db_comment="Categorization of concept purpose (e.g. 'gender', 'observation_type')",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="app_saude.domain",
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="id",
            field=models.AutoField(db_column="person_id", primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="concept",
            name="concept_name",
            field=models.CharField(
                blank=True,
                db_comment="Name of the concept (e.g. 'Feminino', 'Tomar remédio')",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="linkedprovider",
            name="person",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="app_saude.person",
            ),
        ),
        migrations.AlterField(
            model_name="linkedprovider",
            name="provider",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="app_saude.provider",
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="biological_sex",
            field=models.ForeignKey(
                blank=True,
                db_comment="Biological sex a    s a reference to Concept (e.g. Male, Female)",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="app_saude.concept",
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="user",
            field=models.ForeignKey(
                blank=True,
                db_comment="Reference to the base auth_user entity",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="provider",
            name="provider_id",
            field=models.AutoField(
                db_comment="Primary key of the Provider table",
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="provider",
            name="user",
            field=models.ForeignKey(
                blank=True,
                db_comment="Reference to the base auth_user entity",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="linkedprovider",
            unique_together={("person", "provider")},
        ),
    ]
