# Generated by Django 5.2 on 2025-05-02 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_saude", "0004_remove_emergencymessage_person_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="domain",
            name="domain_id",
            field=models.CharField(
                db_comment="Primary key of Domain Class", max_length=100, primary_key=True, serialize=False
            ),
        ),
    ]
