# Generated by Django 5.2 on 2025-05-06 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_saude", "0005_alter_domain_domain_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="concept",
            name="vocabulary_id",
            field=models.ForeignKey(
                blank=True,
                db_comment="Reference to Vocabulary",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="concept_vocabulary_set",
                to="app_saude.vocabulary",
            ),
        ),
    ]
