# Generated by Django 5.2 on 2025-05-08 22:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_saude", "0012_alter_person_user_alter_provider_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="drugexposure",
            name="dose_times",
        ),
        migrations.RemoveField(
            model_name="drugexposure",
            name="interval_hours",
        ),
        migrations.CreateModel(
            name="RecurrenceRule",
            fields=[
                ("recurrence_rule_id", models.AutoField(primary_key=True, serialize=False)),
                ("interval", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "weekday_binary",
                    models.CharField(help_text="String binária com 7 posições: SEG=0, TER=1, ..., SAB=6", max_length=7),
                ),
                ("valid_start_date", models.DateField(auto_now_add=True)),
                ("valid_end_date", models.DateField(default="2099-12-31")),
                (
                    "frequency_concept",
                    models.ForeignKey(
                        limit_choices_to={"concept_class_id": "Frequency", "domain_id": "Recurrence"},
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="recurrence_rules",
                        to="app_saude.concept",
                    ),
                ),
            ],
            options={
                "db_table": "recurrence_rule",
            },
        ),
        migrations.AddField(
            model_name="drugexposure",
            name="recurrence_rule",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="drug_exposures",
                to="app_saude.recurrencerule",
            ),
        ),
        migrations.AddField(
            model_name="visitoccurrence",
            name="recurrence_rule",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="visit_occurrences",
                to="app_saude.recurrencerule",
            ),
        ),
    ]
