# Generated by Django 5.2 on 2025-05-30 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_saude", "0019_alter_provider_professional_registration"),
    ]

    operations = [
        migrations.AddField(
            model_name="observation",
            name="observation_source_value",
            field=models.CharField(blank=True, db_comment="Source value of the observation", max_length=50, null=True),
        ),
    ]
