# Generated by Django 5.2 on 2025-06-09 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_saude", "0022_alter_observation_value_as_string"),
    ]

    operations = [
        migrations.AlterField(
            model_name="factrelationship",
            name="domain_concept_1",
            field=models.ForeignKey(
                db_comment="Domain Concept of first fact",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="factrel_domain_concept_1_set",
                to="app_saude.concept",
            ),
        ),
        migrations.AlterField(
            model_name="factrelationship",
            name="domain_concept_2",
            field=models.ForeignKey(
                db_comment="Domain Concept of second fact",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="factrel_domain_concept_2_set",
                to="app_saude.concept",
            ),
        ),
        migrations.AlterField(
            model_name="factrelationship",
            name="relationship_concept",
            field=models.ForeignKey(
                db_comment="Type of relationship Concept",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="factrel_relationship_concept_set",
                to="app_saude.concept",
            ),
        ),
        migrations.AlterField(
            model_name="measurement",
            name="person",
            field=models.ForeignKey(
                blank=True,
                db_comment="Patient linked to the measurement",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="app_saude.person",
            ),
        ),
        migrations.AlterField(
            model_name="observation",
            name="person",
            field=models.ForeignKey(
                blank=True,
                db_comment="Patient linked to the observation",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="app_saude.person",
            ),
        ),
    ]
