# Generated by Django 5.2 on 2025-06-11 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_saude", "0024_alter_observation_value_as_string"),
    ]

    operations = [
        migrations.AlterField(
            model_name="observation",
            name="observation_source_value",
            field=models.TextField(blank=True, db_comment="Source value of the observation", null=True),
        ),
    ]
