# Generated by Django 5.2 on 2025-06-23 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_saude", "0026_person_use_dark_mode_provider_use_dark_mode"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="conceptsynonym",
            name="id",
        ),
        migrations.AddField(
            model_name="conceptsynonym",
            name="concept_synonym_id",
            field=models.AutoField(db_comment="Primary key of Concept Synonym", primary_key=True, serialize=False),
        ),
    ]
