[tool.semantic_release]
version_source = "tag"
branch = "main"
upload_to_pypi = false
commit_parser = "conventional"
repository = "datasci4citizens/server-saude"
version_variable = ["citizens_project/__init__.py:__version__"]

[tool.semantic_release.changelog.default_templates]
changelog_file = "CHANGELOG.md"

[tool.black]
line-length = 120

[tool.isort]
profile = "black"
line_length = 120
multi_line_output = 3
include_trailing_comma = true

[tool.flake8]
max-line-length = 120
