CREATE TABLE "user" (
  "user_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "first_name" varchar(255),
  "last_name" varchar(255),
  "email" varchar UNIQUE,
  "is_active" boolean
);

CREATE TABLE "address" (
  "address_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "person_id" int,
  "street" varchar(255),
  "number" varchar(10),
  "complement" varchar(255),
  "neighborhood" varchar(255),
  "city" varchar(100),
  "state" varchar(50),
  "postal_code" varchar(20)
);

CREATE TABLE "domain" (
  "domain_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "domain_name" varchar(255),
  "created_at" timestamp(6),
  "updated_at" timestamp(6)
);

CREATE TABLE "concept" (
  "concept_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "concept_name" varchar(255),
  "domain_id" int,
  "created_at" timestamp(6),
  "updated_at" timestamp(6),
  FOREIGN KEY (domain_id) REFERENCES domain(domain_id)
);

CREATE TABLE "care_site" (
  "care_site_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "care_site_name" varchar(255),
  "location_id" int,
  "created_at" timestamp(6),
  "updated_at" timestamp(6)
);

CREATE TABLE "provider" (
  "provider_id" int PRIMARY KEY,
  "user_id" int,
  "social_name" varchar(255),
  "professional_email" varchar UNIQUE,
  "professional_registration" int,
  "created_at" timestamp(6),
  "updated_at" timestamp(6)
);

CREATE TABLE "provider_care_site" (
  "provider_id" int,
  "careSite_id" int
);

CREATE TABLE "provider_concept" (
  "provider_id" int,
  "concept_id" int
);

CREATE TABLE "person" (
  "person_id" int PRIMARY KEY,
  "user_id" int,
  "social_name" varchar(255),
  "birth" date,
  "height" float,
  "weight" float,
  "biological_sex_id" int,
  "gender_identity_id" int,
  "race_concept_id" int,
  "created_at" timestamp(6),
  "updated_at" timestamp(6)
);

CREATE TABLE "linked_provider" (
  "linked_provider_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "person_id" int,
  "provider_id" int
);

CREATE TABLE "observation" (
  "observation_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "person_id" int,
  "observation_concept_id" int,
  "value_as_concept_id" int,
  "value_as_text" text,
  "observation_date" timestamp(6),
  "shared_with_provider" boolean,
  "created_at" timestamp(6),
  "updated_at" timestamp(6)
);

CREATE TABLE "drug_exposure" (
  "drug_exposure_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "person_id" int,
  "drug_concept_id" int,
  "drug_exposure_start_date" date,
  "drug_exposure_end_date" date,
  "stop_reason" varchar(255),
  "quantity" int,
  "interval_hours" int,
  "dose_times" time[],
  "sig" text,
  "created_at" timestamp(6),
  "updated_at" timestamp(6)
);

CREATE TABLE "visit_occurrence" (
  "visit_occurrence_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "person_id" int,
  "provider_id" int,
  "care_site_id" int,
  "visit_date" timestamp(6),
  "visit_end_date" timestamp(6),
  "observations" text,
  "created_at" timestamp(6),
  "updated_at" timestamp(6)
);

CREATE TABLE "emergency_message" (
  "emergency_message_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "person_id" int,
  "message" text,
  "created_at" timestamp(6),
  "updated_at" timestamp(6)
);

CREATE TABLE "emergency_provider" (
  "provider_id" int,
  "emergency_message_id" int,
  "acknowledged" boolean DEFAULT false,
  "response_note" text
);

COMMENT ON TABLE "user" IS 'Generic authentication table, used by both patients (Person) and professionals (Provider).';

COMMENT ON COLUMN "user"."first_name" IS 'User''s given name';

COMMENT ON COLUMN "user"."last_name" IS 'User''s family name';

COMMENT ON COLUMN "user"."email" IS 'Login email, must be unique';

COMMENT ON COLUMN "user"."is_active" IS 'Indicates if the user account is active';

COMMENT ON TABLE "address" IS 'Stores residential address for a person.';

COMMENT ON TABLE "domain" IS 'Reference table for organizing types of concepts.';

COMMENT ON TABLE "concept" IS 'OMOP-compliant table for storing standardized values and custom entries such as habits, tasks, and symptoms.';

COMMENT ON COLUMN "concept"."concept_name" IS 'Name of the concept (e.g. ''Feminino'', ''Tomar remédio'')';

COMMENT ON COLUMN "concept"."domain_id" IS 'Categorization of concept purpose (e.g. ''gender'', ''observation_type'')';

COMMENT ON TABLE "care_site" IS 'Healthcare facility or unit where a provider may be associated. Currently not used in UI, but useful for future multi-site features.';

COMMENT ON TABLE "provider" IS 'Represents a healthcare professional, such as a Community Health Agent (ACS), psychologist, or psychiatrist. Each provider is linked to a User account and may interact with multiple patients through LinkedProvider.';

COMMENT ON COLUMN "provider"."provider_id" IS 'Primary key of the Provider table';

COMMENT ON COLUMN "provider"."user_id" IS 'Reference to the base User entity';

COMMENT ON COLUMN "provider"."social_name" IS 'Optional name used in social or professional contexts';

COMMENT ON COLUMN "provider"."professional_email" IS 'Official work email address of the provider';

COMMENT ON COLUMN "provider"."professional_registration" IS 'Registration number in official professional board (e.g. CRM, CRP, COREN)';

COMMENT ON COLUMN "provider"."created_at" IS 'Record creation timestamp';

COMMENT ON COLUMN "provider"."updated_at" IS 'Last update timestamp';

COMMENT ON TABLE "provider_care_site" IS 'Many-to-many relation between providers and care sites.';

COMMENT ON TABLE "provider_concept" IS 'Represents provider specialities or roles via concepts (e.g. ''Psicólogo'').';

COMMENT ON TABLE "person" IS 'Represents an individual user who is a patient in the system. Each person is linked to a base User account and may optionally declare social identifiers, demographics, and physical attributes. Compatible with OMOP conventions for population-based data.';

COMMENT ON COLUMN "person"."person_id" IS 'Primary key of the Person table';

COMMENT ON COLUMN "person"."user_id" IS 'Reference to the base User entity';

COMMENT ON COLUMN "person"."social_name" IS 'Optional name used by the person in social or preferred contexts';

COMMENT ON COLUMN "person"."birth" IS 'Date of birth';

COMMENT ON COLUMN "person"."height" IS 'Height in meters (or preferred unit)';

COMMENT ON COLUMN "person"."weight" IS 'Weight in kilograms (or preferred unit)';

COMMENT ON COLUMN "person"."biological_sex_id" IS 'Biological sex as a reference to Concept (e.g. Male, Female)';

COMMENT ON COLUMN "person"."gender_identity_id" IS 'Self-declared gender identity as Concept (e.g. Non-binary)';

COMMENT ON COLUMN "person"."race_concept_id" IS 'Self-declared race/ethnicity as Concept';

COMMENT ON COLUMN "person"."created_at" IS 'Record creation timestamp';

COMMENT ON COLUMN "person"."updated_at" IS 'Last update timestamp';

COMMENT ON TABLE "linked_provider" IS 'Links patients to providers. Enables shared visibility of patient data.';

COMMENT ON TABLE "observation" IS 'Core table for capturing all patient-reported or observed data, including symptoms, habits, notes, tasks, etc. OMOP-aligned and extensible.';

COMMENT ON COLUMN "observation"."person_id" IS 'Patient who made or received the observation';

COMMENT ON COLUMN "observation"."observation_concept_id" IS 'What is being observed (e.g., mood, symptom, task)';

COMMENT ON COLUMN "observation"."value_as_concept_id" IS 'Recorded answer, when categorical (e.g., ''Sad'', ''4 times'')';

COMMENT ON COLUMN "observation"."value_as_text" IS 'Free-text input (e.g. diary, thought, notes)';

COMMENT ON COLUMN "observation"."observation_date" IS 'When the observation occurred';

COMMENT ON COLUMN "observation"."shared_with_provider" IS 'Whether this data is visible to the assigned provider';

COMMENT ON TABLE "drug_exposure" IS 'Captures medication prescriptions or usage. Supports structured tracking for reminders, notifications, and clinical follow-up. Aligned with OMOP, with local extensions for real-time alerts based on dosage schedule.';

COMMENT ON COLUMN "drug_exposure"."drug_exposure_id" IS 'Primary key of the drug exposure record';

COMMENT ON COLUMN "drug_exposure"."person_id" IS 'The patient using the medication';

COMMENT ON COLUMN "drug_exposure"."drug_concept_id" IS 'The prescribed or used drug (mapped to a concept)';

COMMENT ON COLUMN "drug_exposure"."drug_exposure_start_date" IS 'Date when the medication regimen begins';

COMMENT ON COLUMN "drug_exposure"."drug_exposure_end_date" IS 'Optional end date for the medication regimen';

COMMENT ON COLUMN "drug_exposure"."stop_reason" IS 'Optional reason for stopping the medication';

COMMENT ON COLUMN "drug_exposure"."quantity" IS 'Total number of units prescribed or dispensed (e.g., 30 pills)';

COMMENT ON COLUMN "drug_exposure"."interval_hours" IS 'Interval between doses in hours (e.g. 8 = every 8 hours)';

COMMENT ON COLUMN "drug_exposure"."dose_times" IS 'Fixed intake times (e.g. [''08:00'', ''20:00''])';

COMMENT ON COLUMN "drug_exposure"."sig" IS 'Free-text instructions for the patient (e.g. ''1x ao dia em jejum'')';

COMMENT ON COLUMN "drug_exposure"."created_at" IS 'Record creation timestamp';

COMMENT ON COLUMN "drug_exposure"."updated_at" IS 'Record update timestamp';

COMMENT ON TABLE "visit_occurrence" IS 'Stores scheduled or completed interactions between a patient and a healthcare professional. Can be used for consultations, check-ins, or assessments. Extensible to multiple providers and care sites.';

COMMENT ON COLUMN "visit_occurrence"."visit_occurrence_id" IS 'Primary key for the visit record';

COMMENT ON COLUMN "visit_occurrence"."person_id" IS 'The patient involved in the visit';

COMMENT ON COLUMN "visit_occurrence"."provider_id" IS 'The healthcare professional attending the visit (optional)';

COMMENT ON COLUMN "visit_occurrence"."care_site_id" IS 'Healthcare location where the visit occurred (optional)';

COMMENT ON COLUMN "visit_occurrence"."visit_date" IS 'Start date and time of the visit';

COMMENT ON COLUMN "visit_occurrence"."visit_end_date" IS 'End date and time of the visit (optional)';

COMMENT ON COLUMN "visit_occurrence"."observations" IS 'Free-text field for summarizing key points or outcomes of the visit';

COMMENT ON COLUMN "visit_occurrence"."created_at" IS 'Timestamp of record creation';

COMMENT ON COLUMN "visit_occurrence"."updated_at" IS 'Timestamp of last update';

COMMENT ON TABLE "emergency_message" IS 'Represents an urgent message initiated by the patient to signal psychological distress or critical situations. Can be shared with one or more providers.';

COMMENT ON COLUMN "emergency_message"."emergency_message_id" IS 'Primary key for the emergency message';

COMMENT ON COLUMN "emergency_message"."person_id" IS 'Patient who triggered the emergency alert';

COMMENT ON COLUMN "emergency_message"."message" IS 'Free-text description of the emergency situation';

COMMENT ON COLUMN "emergency_message"."created_at" IS 'Timestamp when the emergency was reported';

COMMENT ON COLUMN "emergency_message"."updated_at" IS 'Last update time (optional edits or resolutions)';

COMMENT ON TABLE "emergency_provider" IS 'Many-to-many relationship linking emergency alerts to responsible or notified healthcare professionals. Tracks acknowledgment and responses to urgent cases.';

COMMENT ON COLUMN "emergency_provider"."provider_id" IS 'Professional assigned to respond to the emergency';

COMMENT ON COLUMN "emergency_provider"."emergency_message_id" IS 'Emergency message associated with the provider';

COMMENT ON COLUMN "emergency_provider"."acknowledged" IS 'Whether the provider acknowledged the emergency';

COMMENT ON COLUMN "emergency_provider"."response_note" IS 'Optional note or summary written by the provider in response';

ALTER TABLE "address" ADD FOREIGN KEY ("person_id") REFERENCES "person" ("person_id");

ALTER TABLE "provider" ADD FOREIGN KEY ("user_id") REFERENCES "user" ("user_id");

ALTER TABLE "provider_care_site" ADD FOREIGN KEY ("provider_id") REFERENCES "provider" ("provider_id");

ALTER TABLE "provider_care_site" ADD FOREIGN KEY ("careSite_id") REFERENCES "care_site" ("care_site_id");

ALTER TABLE "provider_concept" ADD FOREIGN KEY ("provider_id") REFERENCES "provider" ("provider_id");

ALTER TABLE "provider_concept" ADD FOREIGN KEY ("concept_id") REFERENCES "concept" ("concept_id");

ALTER TABLE "person" ADD FOREIGN KEY ("user_id") REFERENCES "user" ("user_id");

ALTER TABLE "person" ADD FOREIGN KEY ("biological_sex_id") REFERENCES "concept" ("concept_id");

ALTER TABLE "person" ADD FOREIGN KEY ("gender_identity_id") REFERENCES "concept" ("concept_id");

ALTER TABLE "person" ADD FOREIGN KEY ("race_concept_id") REFERENCES "concept" ("concept_id");

ALTER TABLE "linked_provider" ADD FOREIGN KEY ("person_id") REFERENCES "person" ("person_id");

ALTER TABLE "linked_provider" ADD FOREIGN KEY ("provider_id") REFERENCES "provider" ("provider_id");

ALTER TABLE "observation" ADD FOREIGN KEY ("person_id") REFERENCES "person" ("person_id");

ALTER TABLE "observation" ADD FOREIGN KEY ("observation_concept_id") REFERENCES "concept" ("concept_id");

ALTER TABLE "observation" ADD FOREIGN KEY ("value_as_concept_id") REFERENCES "concept" ("concept_id");

ALTER TABLE "drug_exposure" ADD FOREIGN KEY ("person_id") REFERENCES "person" ("person_id");

ALTER TABLE "drug_exposure" ADD FOREIGN KEY ("drug_concept_id") REFERENCES "concept" ("concept_id");

ALTER TABLE "visit_occurrence" ADD FOREIGN KEY ("person_id") REFERENCES "person" ("person_id");

ALTER TABLE "visit_occurrence" ADD FOREIGN KEY ("provider_id") REFERENCES "provider" ("provider_id");

ALTER TABLE "visit_occurrence" ADD FOREIGN KEY ("care_site_id") REFERENCES "care_site" ("care_site_id");

ALTER TABLE "emergency_message" ADD FOREIGN KEY ("person_id") REFERENCES "person" ("person_id");

ALTER TABLE "emergency_provider" ADD FOREIGN KEY ("provider_id") REFERENCES "provider" ("provider_id");

ALTER TABLE "emergency_provider" ADD FOREIGN KEY ("emergency_message_id") REFERENCES "emergency_message" ("emergency_message_id");
