
Project "SAUDE-DB" {
  database_type: "PostgreSQL"
}

Table vocabulary {
  vocabulary_id varchar(20) [pk, note: 'Primary key of Vocabulary']
  vocabulary_name varchar(255) [note: 'Name of the vocabulary']
  vocabulary_concept int [ref: > concept.concept_id, note: 'Reference to Concept representing the vocabulary']
  created_at timestamp [note: 'Creation timestamp']
  updated_at timestamp [note: 'Update timestamp']
}

Table concept_class {
  concept_class_id varchar(20) [pk, note: 'Primary key of Concept Class']
  concept_class_name varchar(255) [note: 'Name of the Concept Class']
  concept_class_concept int [ref: > concept.concept_id, note: 'Reference to Concept representing the Concept Class']
  created_at timestamp [note: 'Creation timestamp']
  updated_at timestamp [note: 'Update timestamp']
}

Table concept {
  concept_id serial [pk, note: 'Primary key of Concept']
  concept_name varchar(255) [note: 'Name of the concept']
  domain int [ref: > domain.domain_id, note: 'Reference to Domain']
  concept_class_id varchar(20) [note: 'Class of the concept']
  concept_code varchar(50) [note: 'Code of the concept in source vocabulary']
  valid_start_date date [note: 'Start date of concept validity']
  valide_end_date date [note: 'End date of concept validity']
  created_at timestamp [note: 'Creation timestamp']
  updated_at timestamp [note: 'Update timestamp']
}

Table concept_synonym {
  concept int [ref: > concept.concept_id, note: 'Reference to Concept']
  concept_synonym_name varchar(1000) [note: 'Synonym name']
  language_concept int [ref: > concept.concept_id, note: 'Language Concept of the synonym']
  created_at timestamp [note: 'Creation timestamp']
  updated_at timestamp [note: 'Update timestamp']
  indexes {
    (concept) [name: 'idx_concept_synonym_id']
  }
}

Table domain {
  domain_id serial [pk, note: 'Primary key of Domain']
  domain_name varchar(255) [note: 'Name of the domain']
  domain_concept int [ref: > concept.concept_id, note: 'Reference to Concept representing the domain']
  created_at timestamp [note: 'Creation timestamp']
  updated_at timestamp [note: 'Update timestamp']
}

Table location {
  location_id serial [pk, note: 'Primary key of Location']
  address_1 varchar(50) [note: 'Street and number']
  address_2 varchar(50) [note: 'Complement']
  city varchar(255) [note: 'City']
  state varchar(255) [note: 'State']
  zip varchar(20) [note: 'Postal code']
  country_concept int [ref: > concept.concept_id, note: 'Country Concept']
  created_at timestamp [note: 'Creation timestamp']
  updated_at timestamp [note: 'Update timestamp']
}

Table person {
  person_id serial [pk, note: 'Primary key of Person']
  user int [note: 'Reference to Django auth_user']
  social_name varchar(255)
  birth_datetime timestamp [note: 'Date and time of birth']
  year_of_birth int [note: 'Year of birth']
  gender_concept int [ref: > concept.concept_id, note: 'Gender Concept']
  ethnicity_concept int [ref: > concept.concept_id, note: 'Ethnicity Concept']
  race_concept int [ref: > concept.concept_id, note: 'Race Concept']
  location int [ref: > location.location_id, note: 'Location of residence']
  created_at timestamp [note: 'Creation timestamp']
  updated_at timestamp [note: 'Update timestamp']
}

Table provider {
  provider_id serial [pk, note: 'Primary key of Provider']
  user int [note: 'Reference to Django auth_user']
  social_name varchar(255)
  birth_datetime timestamp [note: 'Date and time of birth']
  professional_registration int [note: 'Professional registration number']
  specialty_concept int [ref: > concept.concept_id, note: 'Specialty Concept']
  care_site int [ref: > care_site.care_site_id, note: 'Reference to Care Site']
  created_at timestamp [note: 'Creation timestamp']
  updated_at timestamp [note: 'Update timestamp']
}

Table care_site {
  care_site_id serial [pk, note: 'Primary key of Care Site']
  care_site_name varchar(255) [note: 'Name of the Care Site']
  location int [ref: > location.location_id, note: 'Location of Care Site']
  place_of_service_concept int [ref: > concept.concept_id, note: 'Place of Service Concept']
  created_at timestamp [note: 'Creation timestamp']
  updated_at timestamp [note: 'Update timestamp']
}

Table drug_exposure {
  drug_exposure_id serial [pk, note: 'Primary key of Drug Exposure']
  person int [ref: > person.person_id, note: 'Patient receiving the drug']
  drug_concept int [ref: > concept.concept_id, note: 'Drug Concept']
  drug_type_concept int [ref: > concept.concept_id, note: 'Drug Type Concept']
  drug_exposure_start_date date [note: 'Start date of drug exposure']
  drug_exposure_end_date date [note: 'End date of drug exposure']
  stop_reason varchar(255) [note: 'Reason for stopping medication']
  quantity int [note: 'Quantity administered']
  interval_hours int [note: 'Interval between doses in hours']
  dose_times text [note: 'Scheduled dose times']
  sig text [note: 'Free-text dosage instructions']
  created_at timestamp [note: 'Creation timestamp']
  updated_at timestamp [note: 'Update timestamp']
}

Table observation {
  observation_id serial [pk, note: 'Primary key of Observation']
  person int [ref: > person.person_id, note: 'Patient linked to the observation']
  provider int [ref: > provider.provider_id, note: 'Provider attending the visit']
  observation_concept int [ref: > concept.concept_id, note: 'Observation Concept']
  value_as_concept int [ref: > concept.concept_id, note: 'Value as Concept']
  value_as_string varchar(60) [note: 'Free-text value']
  observation_date timestamp [note: 'Date and time of observation']
  observation_type_concept int [ref: > concept.concept_id, note: 'Observation Type Concept']
  shared_with_provider boolean [note: 'Visibility to assigned provider']
  created_at timestamp [note: 'Creation timestamp']
  updated_at timestamp [note: 'Update timestamp']
}

Table visit_occurrence {
  visit_occurrence_id serial [pk, note: 'Primary key of Visit Occurrence']
  person int [ref: > person.person_id, note: 'Patient involved in the visit']
  provider int [ref: > provider.provider_id, note: 'Provider attending the visit']
  care_site int [ref: > care_site.care_site_id, note: 'Care Site location']
  visit_concept int [ref: > concept.concept_id, note: 'Visit Concept']
  visit_start_date timestamp [note: 'Visit start date and time']
  visit_end_date timestamp [note: 'Visit end date and time']
  visit_type_concept int [ref: > concept.concept_id, note: 'Visit Type Concept']
  observations text [note: 'Summary notes of the visit']
  created_at timestamp [note: 'Creation timestamp']
  updated_at timestamp [note: 'Update timestamp']
}

Table measurement {
  measurement_id serial [pk, note: 'Primary key of Measurement']
  person int [ref: > person.person_id, note: 'Patient linked to the measurement']
  measurement_concept int [ref: > concept.concept_id, note: 'Measurement Concept']
  measurement_date timestamp [note: 'Date and time of measurement']
  measurement_type_concept int [ref: > concept.concept_id, note: 'Measurement Type Concept']
  created_at timestamp [note: 'Creation timestamp']
  updated_at timestamp [note: 'Update timestamp']
}

Table fact_relationship {
  domain_concept_id_1 int [ref: > concept.concept_id, note: 'Domain Concept of first fact']
  fact_id_1 int [note: 'ID of first fact']
  domain_concept_id_2 int [ref: > concept.concept_id, note: 'Domain Concept of second fact']
  fact_id_2 int [note: 'ID of second fact']
  relationship_concept int [ref: > concept.concept_id, note: 'Type of relationship Concept']
  created_at timestamp [note: 'Creation timestamp']
  updated_at timestamp [note: 'Update timestamp']
  indexes {
    (fact_id_1, fact_id_2, relationship_concept) [unique]
  }
}
