# Generated by Django 5.2 on 2025-05-06 23:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_saude", "0006_concept_vocabulary_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="concept",
            old_name="concept_class_id",
            new_name="concept_class",
        ),
        migrations.RenameField(
            model_name="concept",
            old_name="vocabulary_id",
            new_name="vocabulary",
        ),
        migrations.AlterField(
            model_name="vocabulary",
            name="vocabulary_concept",
            field=models.ForeignKey(
                blank=True,
                db_comment="Reference to Concept representing the vocabulary",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="vocabulary_concept_set",
                to="app_saude.concept",
            ),
        ),
    ]
