# Generated by Django 5.2 on 2025-05-07 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_saude", "0007_rename_concept_class_id_concept_concept_class_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="concept",
            name="concept_class",
            field=models.ForeignKey(
                blank=True,
                db_comment="Reference to ConceptClass.concept_class_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="app_saude.conceptclass",
            ),
        ),
    ]
