# Generated by Django 5.2 on 2025-05-08 22:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_saude", "0013_remove_drugexposure_dose_times_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recurrencerule",
            name="frequency_concept",
            field=models.ForeignKey(
                limit_choices_to={"concept_class_id": "Recurrence", "domain_id": "Observation"},
                on_delete=django.db.models.deletion.PROTECT,
                related_name="recurrence_rules",
                to="app_saude.concept",
            ),
        ),
    ]
