# Generated by Django 5.2 on 2025-05-08 22:25

from django.db import migrations, models

import app_saude.models


class Migration(migrations.Migration):

    dependencies = [
        ("app_saude", "0014_alter_recurrencerule_frequency_concept"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recurrencerule",
            name="weekday_binary",
            field=models.CharField(
                help_text="String binária com 7 posições: SEG=0, TER=1, ..., SAB=6",
                max_length=7,
                null=True,
                validators=[app_saude.models.validate_weekday_binary],
            ),
        ),
    ]
