# Generated by Django 5.2 on 2025-05-16 01:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_saude", "0017_alter_person_user_alter_provider_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConceptRelationship",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_comment="Creation timestamp")),
                ("updated_at", models.DateTimeField(auto_now=True, db_comment="Update timestamp")),
                ("relationship_id", models.CharField(max_length=100)),
                (
                    "concept_1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="source_concept_rels",
                        to="app_saude.concept",
                    ),
                ),
                (
                    "concept_2",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="target_concept_rels",
                        to="app_saude.concept",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
