# Generated by Django 5.2 on 2025-05-30 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_saude", "0018_conceptrelationship"),
    ]

    operations = [
        migrations.AlterField(
            model_name="provider",
            name="professional_registration",
            field=models.IntegerField(
                blank=True, db_comment="Professional registration number", default=123, unique=True
            ),
            preserve_default=False,
        ),
    ]
