# Generated by Django 5.2 on 2025-06-09 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_saude", "0020_observation_observation_source_value"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="profile_picture",
            field=models.CharField(blank=True, db_comment="URL of the profile picture", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="provider",
            name="profile_picture",
            field=models.CharField(blank=True, db_comment="URL of the profile picture", max_length=255, null=True),
        ),
    ]
