# Generated by Django 5.2 on 2025-06-11 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_saude", "0023_alter_factrelationship_domain_concept_1_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="observation",
            name="value_as_string",
            field=models.TextField(blank=True, db_comment="Free-text value", null=True),
        ),
    ]
