# Generated by Django 5.2 on 2025-06-10 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_saude", "0023_alter_factrelationship_domain_concept_1_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="observation",
            name="observation_source_value",
            field=models.CharField(blank=True, db_comment="Source value of the observation", max_length=100, null=True),
        ),
    ]
