# Generated by Django 5.2 on 2025-06-22 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_saude", "0025_alter_observation_observation_source_value"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="use_dark_mode",
            field=models.BooleanField(db_comment="Indicates if the user prefers dark mode", default=False),
        ),
        migrations.AddField(
            model_name="provider",
            name="use_dark_mode",
            field=models.BooleanField(db_comment="Indicates if the user prefers dark mode", default=False),
        ),
    ]
