name: Commit Lint

on:
  push:
    branches: [main, develop, '**']

jobs:
  lint-commits:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install commitlint
        run: |
          npm install --save-dev commitlint @commitlint/config-conventional

      - name: Create commitlint config
        run: |
          echo "module.exports = $(cat commitlint.config.js)" > commitlint.config.js

      - name: Fetch history
        run: git fetch --unshallow || true

      - name: Lint commits
        run: |
          git fetch origin ${{ github.base_ref || 'main' }}
          BASE=$(git merge-base origin/${{ github.base_ref || 'main' }} HEAD)
          echo "Linting commits from $BASE to HEAD"
          npx commitlint --from=$BASE --to=HEAD